// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MapWorkerClient is the client API for MapWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapWorkerClient interface {
	Map(ctx context.Context, in *MapTask, opts ...grpc.CallOption) (MapWorker_MapClient, error)
	Get(ctx context.Context, in *Region, opts ...grpc.CallOption) (MapWorker_GetClient, error)
}

type mapWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewMapWorkerClient(cc grpc.ClientConnInterface) MapWorkerClient {
	return &mapWorkerClient{cc}
}

func (c *mapWorkerClient) Map(ctx context.Context, in *MapTask, opts ...grpc.CallOption) (MapWorker_MapClient, error) {
	stream, err := c.cc.NewStream(ctx, &MapWorker_ServiceDesc.Streams[0], "/MapWorker/Map", opts...)
	if err != nil {
		return nil, err
	}
	x := &mapWorkerMapClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MapWorker_MapClient interface {
	Recv() (*MapTaskStatus, error)
	grpc.ClientStream
}

type mapWorkerMapClient struct {
	grpc.ClientStream
}

func (x *mapWorkerMapClient) Recv() (*MapTaskStatus, error) {
	m := new(MapTaskStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mapWorkerClient) Get(ctx context.Context, in *Region, opts ...grpc.CallOption) (MapWorker_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &MapWorker_ServiceDesc.Streams[1], "/MapWorker/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &mapWorkerGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MapWorker_GetClient interface {
	Recv() (*Pair, error)
	grpc.ClientStream
}

type mapWorkerGetClient struct {
	grpc.ClientStream
}

func (x *mapWorkerGetClient) Recv() (*Pair, error) {
	m := new(Pair)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MapWorkerServer is the server API for MapWorker service.
// All implementations must embed UnimplementedMapWorkerServer
// for forward compatibility
type MapWorkerServer interface {
	Map(*MapTask, MapWorker_MapServer) error
	Get(*Region, MapWorker_GetServer) error
	mustEmbedUnimplementedMapWorkerServer()
}

// UnimplementedMapWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedMapWorkerServer struct {
}

func (UnimplementedMapWorkerServer) Map(*MapTask, MapWorker_MapServer) error {
	return status.Errorf(codes.Unimplemented, "method Map not implemented")
}
func (UnimplementedMapWorkerServer) Get(*Region, MapWorker_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMapWorkerServer) mustEmbedUnimplementedMapWorkerServer() {}

// UnsafeMapWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapWorkerServer will
// result in compilation errors.
type UnsafeMapWorkerServer interface {
	mustEmbedUnimplementedMapWorkerServer()
}

func RegisterMapWorkerServer(s grpc.ServiceRegistrar, srv MapWorkerServer) {
	s.RegisterService(&MapWorker_ServiceDesc, srv)
}

func _MapWorker_Map_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MapTask)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MapWorkerServer).Map(m, &mapWorkerMapServer{stream})
}

type MapWorker_MapServer interface {
	Send(*MapTaskStatus) error
	grpc.ServerStream
}

type mapWorkerMapServer struct {
	grpc.ServerStream
}

func (x *mapWorkerMapServer) Send(m *MapTaskStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _MapWorker_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Region)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MapWorkerServer).Get(m, &mapWorkerGetServer{stream})
}

type MapWorker_GetServer interface {
	Send(*Pair) error
	grpc.ServerStream
}

type mapWorkerGetServer struct {
	grpc.ServerStream
}

func (x *mapWorkerGetServer) Send(m *Pair) error {
	return x.ServerStream.SendMsg(m)
}

// MapWorker_ServiceDesc is the grpc.ServiceDesc for MapWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MapWorker",
	HandlerType: (*MapWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Map",
			Handler:       _MapWorker_Map_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _MapWorker_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine/api/worker.proto",
}

// ReduceWorkerClient is the client API for ReduceWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReduceWorkerClient interface {
	Reduce(ctx context.Context, in *ReduceTask, opts ...grpc.CallOption) (ReduceWorker_ReduceClient, error)
	Notify(ctx context.Context, opts ...grpc.CallOption) (ReduceWorker_NotifyClient, error)
}

type reduceWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewReduceWorkerClient(cc grpc.ClientConnInterface) ReduceWorkerClient {
	return &reduceWorkerClient{cc}
}

func (c *reduceWorkerClient) Reduce(ctx context.Context, in *ReduceTask, opts ...grpc.CallOption) (ReduceWorker_ReduceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReduceWorker_ServiceDesc.Streams[0], "/ReduceWorker/Reduce", opts...)
	if err != nil {
		return nil, err
	}
	x := &reduceWorkerReduceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReduceWorker_ReduceClient interface {
	Recv() (*ReduceTaskStatus, error)
	grpc.ClientStream
}

type reduceWorkerReduceClient struct {
	grpc.ClientStream
}

func (x *reduceWorkerReduceClient) Recv() (*ReduceTaskStatus, error) {
	m := new(ReduceTaskStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reduceWorkerClient) Notify(ctx context.Context, opts ...grpc.CallOption) (ReduceWorker_NotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReduceWorker_ServiceDesc.Streams[1], "/ReduceWorker/Notify", opts...)
	if err != nil {
		return nil, err
	}
	x := &reduceWorkerNotifyClient{stream}
	return x, nil
}

type ReduceWorker_NotifyClient interface {
	Send(*Region) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type reduceWorkerNotifyClient struct {
	grpc.ClientStream
}

func (x *reduceWorkerNotifyClient) Send(m *Region) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reduceWorkerNotifyClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReduceWorkerServer is the server API for ReduceWorker service.
// All implementations must embed UnimplementedReduceWorkerServer
// for forward compatibility
type ReduceWorkerServer interface {
	Reduce(*ReduceTask, ReduceWorker_ReduceServer) error
	Notify(ReduceWorker_NotifyServer) error
	mustEmbedUnimplementedReduceWorkerServer()
}

// UnimplementedReduceWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedReduceWorkerServer struct {
}

func (UnimplementedReduceWorkerServer) Reduce(*ReduceTask, ReduceWorker_ReduceServer) error {
	return status.Errorf(codes.Unimplemented, "method Reduce not implemented")
}
func (UnimplementedReduceWorkerServer) Notify(ReduceWorker_NotifyServer) error {
	return status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedReduceWorkerServer) mustEmbedUnimplementedReduceWorkerServer() {}

// UnsafeReduceWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReduceWorkerServer will
// result in compilation errors.
type UnsafeReduceWorkerServer interface {
	mustEmbedUnimplementedReduceWorkerServer()
}

func RegisterReduceWorkerServer(s grpc.ServiceRegistrar, srv ReduceWorkerServer) {
	s.RegisterService(&ReduceWorker_ServiceDesc, srv)
}

func _ReduceWorker_Reduce_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReduceTask)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReduceWorkerServer).Reduce(m, &reduceWorkerReduceServer{stream})
}

type ReduceWorker_ReduceServer interface {
	Send(*ReduceTaskStatus) error
	grpc.ServerStream
}

type reduceWorkerReduceServer struct {
	grpc.ServerStream
}

func (x *reduceWorkerReduceServer) Send(m *ReduceTaskStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _ReduceWorker_Notify_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReduceWorkerServer).Notify(&reduceWorkerNotifyServer{stream})
}

type ReduceWorker_NotifyServer interface {
	SendAndClose(*Empty) error
	Recv() (*Region, error)
	grpc.ServerStream
}

type reduceWorkerNotifyServer struct {
	grpc.ServerStream
}

func (x *reduceWorkerNotifyServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reduceWorkerNotifyServer) Recv() (*Region, error) {
	m := new(Region)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReduceWorker_ServiceDesc is the grpc.ServiceDesc for ReduceWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReduceWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReduceWorker",
	HandlerType: (*ReduceWorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Reduce",
			Handler:       _ReduceWorker_Reduce_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Notify",
			Handler:       _ReduceWorker_Notify_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "engine/api/worker.proto",
}
